# https://github.com/actions/labeler
---
area/ci:
  - .github/**

area/msgpack:
  - msgpack/**/*.go

area/nvim:
  - nvim/**/*.go

area/gomod:
  - any['go.mod', 'go.sum']

documentation:
  - "**/*.md"
